#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  selector:
    app: demo   # هر دو نسخه را شامل می‌شود
    version: blue
  ports:
    - port: 80
      targetPort: 80
